SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/mac_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkMult.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkMult
MODULE   := mac

include $(shell cocotb-config --makefiles)/Makefile.sim
